baseurl = "https://blog.daisukekonishi.com/"
languageCode = "ja"
title = "PengNote"
copyright = "(c) 2018 PengNote"
canonifyurls = true
paginate = 3

uglyurl=true
googleAnalytics = "UA-53106421-1"

[params]
  description = "勉強した事や行った場所の感想を書くブログ"
  author = "Daisuke KONISHI"
  twitter = "skd_nw"

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.global]]
    name = "カテゴリ"
    url = "/categories/"

[[menu.global]]
    name = "タグ"
    url = "/tags/"

[[menu.global]]
    name = "About"
    url = "/page/about/"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
