# baseURL = "localhost:1313"
baseURL = 'https://blog.daisukekonishi.com/'
languageCode = "ja"
title = "PengNote"
copyright = "&copy; 2017 PengNote"

uglyURLs = true
hrefTargetBlank = true

[Params]
    subtitle = "勉強した事や行った場所の感想を書くブログ"
    description = "勉強した事や行った場所の感想を書くブログ"
    localeOgp = "ja_JP"

[Author]
    # Social accounts. Link to these accounts are displayed in the header and
    # footer.
    name = "Daisuke Konishi"
    twitter = "skd_nw"
    # github = "d-kusk"

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3
