baseurl = "https://blog.daisukekonishi.com/"
languageCode = "ja"
title = "PengNote"
copyright = "(c) 2017 PengNote"
canonifyurls = true
paginate = 3

uglyURLs = true
hrefTargetBlank = true
googleAnalytics = "UA-53106421-1"

[params]
  description = "勉強した事や行った場所の感想を書くブログ"
  author = "Daisuke KONISHI"
  twitter = "skd_nw"

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.global]]
    name = "クリエイティブ"
    url = "/categories/クリエイティブ/"

[[menu.global]]
    name = "行ったとこ"
    url = "/categories/行ったとこ/"

[[menu.footer]]
    name = "About"
    url = "/page/about/"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
